version: "3.9"

services:
  db:
    image: postgis/postgis:16-3.4
    container_name: kanko_db
    restart: always
    environment:
      POSTGRES_DB: kanko_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: kanko_api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/workspace
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:password@db:5432/kanko_db
    depends_on:
      - db

volumes:
  postgres_data: